[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "vim-airline/vim-airline"
depends = "vim-airline-themes"
hook_add = '''
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#formatter = 'unique_tail'
'''

[[plugins]]
repo = "vim-airline/vim-airline-themes"
hook_add = "let g:airline_theme='jellybeans'"

[[plugins]]
repo = "tomasr/molokai"
hook_add = "colorscheme molokai"

[[plugins]]
repo = "roxma/nvim-yarp"
if = "!has('nvim')"

[[plugins]]
repo = "roxma/vim-hug-neovim-rpc"
if = "!has('nvim')"

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = "preservim/nerdtree"

[[plugins]]
repo = "vim-jp/vimdoc-ja"
