[[plugins]]
repo = ""
on_event = "VimEnter"

[[plugins]]
repo = "Shougo/deoplete.nvim"
on_event = "InsertEnter"
hook_add = '''
    let g:deoplete#enable_at_startup=1
    set completeopt-=preview
'''

[[plugins]]
repo = "Shougo/neosnippet.vim"
on_event = "InsertEnter"
hook_add = '''
    imap <C-k>     <Plug>(neosnippet_expand_or_jump)
    smap <C-k>     <Plug>(neosnippet_expand_or_jump)
    xmap <C-k>     <Plug>(neosnippet_expand_target)
    smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
'''

[[plugins]]
repo = "Shougo/neosnippet-snippets"
on_event = "InsertEnter"

[[plugins]]
repo = "cespare/vim-toml"
on_ft = "toml"
