[[plugins]]
repo = "cespare/vim-toml"
on_ft = "toml"

[[plugins]]
repo = "tpope/vim-surround"
on_ft = ['html', 'xml', 'markdown', 'javascript', 'javascriptreact']

[[plugins]]
repo = "preservim/nerdtree"
on_cmd = "NERDTree"
